image: archlinux/base:latest

stages:
  - prechecks
  - makepkg
  - pre-release
  - build_iso
  - release
  - clean

before_script:
  - pacman-key --init && \
    pacman-key --populate archlinux || true
  - pacman -Sy --noconfirm reflector
  - reflector --verbose --latest 50 --sort rate --save /etc/pacman.d/mirrorlist 
  - pacman -Su --noconfirm

.build_packages_template: &buildpackages
  script:
    - pacman -S --noconfirm --needed mkinitcpio asp base-devel ccache haveged namcap wget sed dos2unix
    - sed -i 's/#MAKEFLAGS="-j2"/MAKEFLAGS="-j'$(nproc)'"/' /etc/makepkg.conf
    - sed -ri 's/^BUILDENV=(.*)\!ccache(.*)/BUILDENV=\1ccache\2/' /etc/makepkg.conf
    - mkdir -p work/cache/ccache work/output
    - ln -s "$(pwd)"/work /work
    - cp packages_*.lst buildContainer.sh /work
    - cp -R package /work
    - useradd -ms /bin/bash -d /work build
    - echo 'build ALL=(root) NOPASSWD:ALL' > /etc/sudoers.d/user && chmod 0440 /etc/sudoers.d/user
    - chown -R build:build work /work
    - chmod -R 777 work /work
    - CCACHE_DIR=/work/cache/ccache ccache -s
    - su - build -c "cd /work && MAKEPKG_OPTS=\"$MAKEPKG_OPTS\" ./buildContainer.sh" 2>&1 | tee work/output/build.log
    - CCACHE_DIR=/work/cache/ccache ccache -s
  cache:
    key: one-key-to-rule-them-all
    paths:
      - work/cache
  artifacts:
    paths:
      - work/output
    expire_in: 1 mos

.build_groovyarcade_iso_template: &buildgroovyarcadeiso
  stage: build_iso
  script:
    - echo "Building iso"
    - pacman -S --noconfirm --needed archiso mkinitcpio cdrtools wget
    - whoami
    - ./buildGA.sh
  artifacts:
    paths:
      - work/output/*.iso.xz
    expire_in: 1 mos

.branches_but_master: &notmaster
  only:
    - branches
  except:
    - master
  when: manual

.only_master: &onlymasterortags
  only:
    - master
    - tags

.only_tags_template: &onlytags
  only:
    - tags

.setup_github_release_template: &setup_github_release
  script:
    - pacman -S --noconfirm --needed tar xz grep
    - curl -L https://github.com/aktau/github-release/releases/download/v0.7.2/linux-amd64-github-release.tar.bz2 | tar -jx --strip-components 3 -C /usr/local/bin bin/linux/amd64/github-release
  

bash_lint:
  image: koalaman/shellcheck-alpine
  stage: prechecks
  allow_failure: true
  when: always
  before_script:
    - shellcheck -V
  script:
    - shellcheck -x *.sh

basic_checks:
  stage: prechecks
  <<: *notmaster
  when: always
  variables:
    MAKEPKG_OPTS: "--nobuild --nodeps"
  <<: *buildpackages

build_packages_manual:
  stage: makepkg
  <<: *notmaster
  <<: *buildpackages
  tags:
    - bigCPU

build_packages:
  stage: makepkg
  <<: *onlymasterortags
  <<: *buildpackages
  tags:
    - bigCPU

prepare_release:
  stage: pre-release
  <<: *onlytags
  <<: *setup_github_release
  script:
    - ./release.sh -c

prepare_release_manual:
  stage: pre-release
  <<: *notmaster
  <<: *setup_github_release
  script:
    - ./release.sh -c


build_iso_manual:
  dependencies: 
    - build_packages_manual
  <<: *notmaster
  <<: *buildgroovyarcadeiso

build_iso:
  <<: *onlymasterortags
  <<: *buildgroovyarcadeiso

upload_assets:
  stage: release
  <<: *onlytags
  <<: *setup_github_release
  script:
    - ./release.sh -u

release_github:
  stage: release
  <<: *onlytags
  <<: *setup_github_release
  script:
    - ./release.sh -p

release_github_manual:
  stage: release
  dependencies: 
    - build_iso_manual
  <<: *notmaster
  <<: *setup_github_release
  script:
    - ./release.sh -p

delete_release:
  stage: clean
  <<: *notmaster
  <<: *setup_github_release
  when: on_failure
  script:
    - ./release.sh -d || true
