image: archlinux/base:latest

stages:
  - makepkg
  - build_iso
  - release



before_script:
  - pacman-key --init && \
    pacman-key --populate archlinux && \
    pacman -Sy
  

create_packages:
  stage: makepkg
  script:
    - pacman -Sy --noconfirm --needed mkinitcpio asp base-devel ccache haveged namcap wget
    - sed -i 's/#MAKEFLAGS="-j2"/MAKEFLAGS="-j'$(nproc)'"/' /etc/makepkg.conf
    - sed -ri 's/^BUILDENV=(.*)\!ccache(.*)/BUILDENV=\1ccache\2/' /etc/makepkg.conf
    - mkdir -p work/cache/ccache
    - ln -s "$(pwd)"/work /work
    - cp packages_*.lst buildContainer.sh /work
    - cp -R package /work
    - useradd -ms /bin/bash -d /work build
    - echo 'build ALL=(root) NOPASSWD:ALL' > /etc/sudoers.d/user && chmod 0440 /etc/sudoers.d/user
    - chown -R build:build work /work
    - chmod -R 777 work /work
    - CCACHE_DIR=/work/cache/ccache ccache -s
    - cat /proc/cpuinfo
    - su - build -c "cd /work && ./buildContainer.sh"
    - CCACHE_DIR=/work/cache/ccache ccache -s
  cache:
    key: one-key-to-rule-them-all
    paths:
      - work/cache
  artifacts:
    paths:
      - work/output
    expire_in: 3 mos

build_groovyarcade_iso:
  stage: build_iso
  script:
    - echo "Building iso"
    - pacman -Sy --noconfirm --needed archiso mkinitcpio cdrtools wget
    - whoami
    - ./buildGA.sh
  artifacts:
    paths:
      - work/output/*.iso
    expire_in: 3 mos

release_github:
  stage: release
  script:
    - echo "Releasing GroovyArcade"
    - pacman -Sy --noconfirm --needed tar
    - curl -L https://github.com/aktau/github-release/releases/download/v0.7.2/linux-amd64-github-release.tar.bz2 | tar -jx --strip-components 3 -C /usr/local/bin bin/linux/amd64/github-release