image: archlinux/base:latest

stages:
  - makepkg
  - build_iso
  - release

cache:
  paths:
  - /work/cache
  - /var/cache/pacman/pkg/

before_script:
  - pacman-key --init && \
    pacman-key --populate archlinux && \
    pacman -Sy
  - pacman -Sy --noconfirm --needed archiso mkinitcpio cdrtools asp base-devel ccache haveged namcap wget
  - curl -L https://github.com/aktau/github-release/releases/download/v0.7.2/linux-amd64-github-release.tar.bz2 | tar -jx --strip-components 3 -C /usr/local/bin bin/linux/amd64/github-release
  - sed -i 's/#MAKEFLAGS="-j2"/MAKEFLAGS="-j'$(nproc)'"/' /etc/makepkg.conf
  - sed -ri 's/^BUILDENV=(.*)\!ccache(.*)/BUILDENV=\1ccache\2/' /etc/makepkg.conf

create_packages:
  stage: makepkg
  script:
    - useradd -ms /bin/bash -d /work build
    - echo 'build ALL=(root) NOPASSWD:ALL' > /etc/sudoers.d/user && chmod 0440 /etc/sudoers.d/user
    - mkdir -p /work /work/cache/ccache"
    - cp packages_*.lst buildContainer.sh /work"
    - cp -R package /work"
    - chown -R build:build /work
    - su - build -c "cd /work && ./buildContainer.sh"

build_groovyarcade_iso:
  stage: build_iso
  script:
    - echo "Building iso"
    - ./buildGA.sh

release_github:
  stage: release
  script:
    - echo "Releasing GroovyArcade"