#!/bin/bash

# GROOVYARCADE details
export GA_VERSION=test
if [[ ! -z ${CI_COMMIT_TAG} ]] ; then
  GA_VERSION=${CI_COMMIT_TAG}
elif [[ ! -z ${CI_COMMIT_SHORT_SHA} ]] ; then
  GA_VERSION=${CI_COMMIT_SHORT_SHA}
fi

# ARCHLINUX version
export ARCH_VERSION=2019.04.01
export ARCH_URL=http://archlinux.mirrors.ovh.net/archlinux
